# Generates behavior and resource pack files.
from os import path
import dotenv
import os
import glob
import json
import mclang
import copy

dotenv.load_dotenv()

PROJECT_NAME = os.getenv("PROJECT_NAME")
PROJECT_ID = os.getenv("PROJECT_ID")
if not PROJECT_NAME:
    raise Exception("PROJECT_NAME not in .env!")
if not PROJECT_ID:
    raise Exception("PROJECT_ID not in .env!")

RP = path.join("resource_packs", PROJECT_NAME)
BP = path.join("behavior_packs", PROJECT_NAME)


def get_type(id: str) -> str:
    if "pale" in id:
        if "redstone_jack_o_lantern" in id:
            return "pale_redstone_jack_o_lantern"
        if "soul_jack_o_lantern" in id:
            return "pale_soul_jack_o_lantern"
        if "copper_jack_o_lantern" in id:
            return "pale_copper_jack_o_lantern"
        if "jack_o_lantern" in id:
            return "pale_jack_o_lantern"
        if "carved_pumpkin" in id:
            return "pale_carved_pumpkin"
    if "soul_jack_o_lantern" in id:
        return "soul_jack_o_lantern"
    if "copper_jack_o_lantern" in id:
        return "copper_jack_o_lantern"
    if "redstone_jack_o_lantern" in id:
        return "redstone_jack_o_lantern"
    if "jack_o_lantern" in id:
        return "jack_o_lantern"
    if "carved" in id:
        return "carved_pumpkin"
    return "pumpkin"


def get_material(id: str) -> str:
    if "pale" in id:
        return "pale_pumpkin"
    return "pumpkin"


def abbr(name: str) -> str:
    return "".join(word[0] for word in name.split("_") if word)


def get_torch(type: str) -> str:
    if "soul" in type:
        return "minecraft:soul_torch"
    if "redstone" in type:
        return "minecraft:redstone_torch"
    if "copper" in type:
        return "minecraft:copper_torch"
    return "minecraft:torch"


def get_pattern(id: str) -> str:
    return (
        id.replace(f"{PROJECT_ID}:", "")
        .replace("_jack_o_lantern", "")
        .replace("_carved_pumpkin", "")
        .replace("_soul", "")
        .replace("_copper", "")
        .replace("_redstone", "")
    )


block_path = path.join(BP, "blocks", "lpsm", PROJECT_NAME, "gen")
os.makedirs(block_path, exist_ok=True)

loot_path = path.join(BP, "loot_tables", "lpsm", PROJECT_NAME, "blocks", "gen")
os.makedirs(loot_path, exist_ok=True)

recipe_path = path.join(BP, "recipes", "lpsm", PROJECT_NAME, "gen")
os.makedirs(recipe_path, exist_ok=True)

texture_root = path.join(RP, "textures", "lpsm", PROJECT_NAME, "blocks")
terrain_texture = {
    "resource_pack_name": "vanilla",
    "texture_name": "atlas.terrain",
    "padding": 8,
    "num_mip_levels": 4,
    "texture_data": {
        "lpsm_more_pumpkins:pale_pumpkin_top": {
            "textures": ["textures/lpsm/more_pumpkins/blocks/pale_pumpkin_top"]
        },
        "lpsm_more_pumpkins:pale_pumpkin_side": {
            "textures": ["textures/lpsm/more_pumpkins/blocks/pale_pumpkin_side"]
        },
    },
}
blocks: dict[str, str | dict] = {
    "format_version": "1.21.40",
    "lpsm_more_pumpkins:pale_pumpkin": {"sound": "wood"},
}

variants: dict[str, list[str]] = {}

textures = glob.glob(path.join(texture_root, "*\\*.png"), recursive=True)

# Load lang
with mclang.open(path.join(RP, "texts", "en_US.lang")) as lang:
    ...

# Remove autogenerated translations
for k in lang.copy().keys():
    if k == "tile.lpsm_more_pumpkins:pale_pumpkin.name":
        continue
    if k.startswith("tile."):
        del lang[k]


# Find type variants (used for stonecutting)
for texture in textures:
    pth, ext = path.splitext(path.relpath(texture, texture_root))
    name = path.basename(pth)
    id = f"lpsm_more_pumpkins:{name}"
    type = get_type(id)

    if type not in variants:
        variants[type] = [name]
        continue
    variants[type].append(name)


# Generate files
for texture in textures:
    pth, ext = path.splitext(path.relpath(texture, texture_root))
    name = path.basename(pth)
    id = f"lpsm_more_pumpkins:{name}"
    type = get_type(id)
    pattern = get_pattern(id)
    mat = get_material(id)
    lit = "jack_o_lantern" in id
    print(id)

    # Terrain Textures
    terrain_texture["texture_data"][id] = {
        "textures": [path.relpath(texture, RP).replace(path.sep, "/")]
    }

    # Sound
    blocks[id] = {"sound": "wood"}

    # Loot table
    loot_fp = path.join(loot_path, f"{name}.json")
    loot = {
        "pools": [{"rolls": 1, "entries": [{"type": "item", "name": id, "weight": 1}]}]
    }
    with open(loot_fp, "w") as fd:
        json.dump(loot, fd, indent=2)

    # Block
    block_fp = path.join(block_path, f"{name}.json")
    material_instances = {
        "*": {"texture": "minecraft:pumpkin_side", "face_dimming": not lit},
        "south": {"texture": id, "face_dimming": not lit},
        "up": {"texture": "minecraft:pumpkin_top", "face_dimming": not lit},
        "down": {"texture": "minecraft:pumpkin_top", "face_dimming": not lit},
    }

    if "pale" in mat:
        material_instances["*"] = {"texture": f"{ PROJECT_ID }:pale_pumpkin_side"}
        material_instances["up"] = {"texture": f"{ PROJECT_ID }:pale_pumpkin_top"}
        material_instances["down"] = {"texture": f"{ PROJECT_ID }:pale_pumpkin_top"}

    block = {
        "format_version": "1.21.110",
        "minecraft:block": {
            "description": {
                "identifier": id,
                "traits": {
                    "minecraft:placement_direction": {
                        "enabled_states": ["minecraft:cardinal_direction"],
                        "y_rotation_offset": 180,
                    },
                },
                "menu_category": {
                    "category": "nature",
                    "group": f"lpsm_more_pumpkins:itemGroup.name.{ type }",
                },
            },
            "components": {
                "tag:minecraft:is_axe_item_destructible": {},
                "minecraft:loot": path.relpath(loot_fp, BP).replace(path.sep, "/"),
                "minecraft:destructible_by_mining": {"seconds_to_destroy": 1},
                "minecraft:destructible_by_explosion": {"explosion_resistance": 1},
                "minecraft:geometry": "minecraft:geometry.full_block",
                "minecraft:map_color": '#D87F33',
                "minecraft:material_instances": material_instances,
            },
            "permutations": [
                {
                    "condition": "q.block_state('minecraft:cardinal_direction')=='north'",
                    "components": {
                        "minecraft:transformation": {"rotation": [0, 180, 0]}
                    },
                },
                {
                    "condition": "q.block_state('minecraft:cardinal_direction')=='south'",
                    "components": {"minecraft:transformation": {"rotation": [0, 0, 0]}},
                },
                {
                    "condition": "q.block_state('minecraft:cardinal_direction')=='east'",
                    "components": {
                        "minecraft:transformation": {"rotation": [0, 90, 0]}
                    },
                },
                {
                    "condition": "q.block_state('minecraft:cardinal_direction')=='west'",
                    "components": {
                        "minecraft:transformation": {"rotation": [0, -90, 0]}
                    },
                },
            ],
        },
    }

    if "jack_o_lantern" in type and "redstone" not in type:
        if "soul" in type:
            block["minecraft:block"]["components"]["minecraft:light_emission"] = 10
        elif 'copper' in type:
            block["minecraft:block"]["components"]["minecraft:light_emission"] = 14
        else:
            block["minecraft:block"]["components"]["minecraft:light_emission"] = 15

    if "redstone" in type:
        # Add states
        block["minecraft:block"]["description"]["states"] = {
            f"{PROJECT_ID}:lit": [False, True]
        }

        # Add components
        block["minecraft:block"]["components"]["minecraft:tick"] = {
            "interval_range": [0, 0]
        }
        block["minecraft:block"]["components"][
            f"{PROJECT_ID}:redstone_jack_o_lantern"
        ] = {}

        # Add permutation
        perm_mat = copy.deepcopy(
            block["minecraft:block"]["components"]["minecraft:material_instances"]
        )
        s_tex = f"{PROJECT_ID}:{pattern }_carved_pumpkin"
        if s_tex == f'{PROJECT_ID}:redstone_carved_pumpkin':
            s_tex = 'minecraft:carved_pumpkin'
            
        block["minecraft:block"]["components"]["minecraft:material_instances"]["south"][
            "texture"
        ] = s_tex
        perm = {
            "condition": f"q.block_state('{ PROJECT_ID }:lit')",
            "components": {
                "minecraft:material_instances": perm_mat,
                "minecraft:light_emission": 15,
            },
        }
        # perm = {"condition": f"q.block_state('{ PROJECT_ID }:lit')", "components": {"minecraft:material_instances": {}, "minecraft:light_emission": 15}}
        block["minecraft:block"]["permutations"].append(perm)

    if "pale" in mat:
        block["minecraft:block"]["components"]["minecraft:map_color"] = '#999999'

    block["minecraft:block"]["components"][f"tag:{ PROJECT_ID }:{ type }"] = {}
    with open(block_fp, "w") as fd:
        json.dump(block, fd, indent=2)

    # Translation
    translation_key = f"tile.{id}.name"
    translation_value = name.replace("_", " ").title().replace("O Lantern", "o'Lantern")
    lang[translation_key] = f"{ translation_value }\\n§vMore Pumpkins Add-On§r"

    # Crafting Recipes
    crafting_fp = path.join(recipe_path, f"{name}.json")
    crafting = None
    if "jack_o_lantern" in type:
        torch = get_torch(type)

        pumpkin = (
            id.replace("redstone_jack_o_lantern", "carved_pumpkin")
            .replace("soul_jack_o_lantern", "carved_pumpkin")
            .replace("copper_jack_o_lantern", "carved_pumpkin")
            .replace("jack_o_lantern", "carved_pumpkin")
        )
        if pumpkin == f"{PROJECT_ID}:carved_pumpkin":
            pumpkin = "minecraft:carved_pumpkin"
        # if "pale" in type:
        #     pumpkin = f"{PROJECT_ID}:pale_carved_pumpkin"
        crafting = {
            "format_version": "1.21.110",
            "minecraft:recipe_shaped": {
                "description": {"identifier": id},
                "tags": ["crafting_table"],
                "pattern": ["P", "T"],
                "key": {"P": {"item": pumpkin}, "T": {"item": torch}},
                "result": {"item": id},
                "unlock": [{"item": torch}],
            },
        }

    if crafting is not None:
        with open(crafting_fp, "w") as fd:
            json.dump(crafting, fd, indent=2)


with open(path.join(RP, "textures", "terrain_texture.json"), "w") as fd:
    json.dump(terrain_texture, fd, indent=2)

with open(path.join(RP, "blocks.json"), "w") as fd:
    json.dump(blocks, fd, indent=2)

lang.save(path.join(RP, "texts", "en_US.lang"))
