package dev.lpsmods.morepumpkins.core;

import dev.lpsmods.morepumpkins.Constants;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;

/**
 * Author: legopitstop
 */
public class ModCreativeModeTabs {
    public static CreativeModeTab MAIN;

    private static CreativeModeTab registerTab(String name, CreativeModeTab tab) {
        return Registry.register(BuiltInRegistries.CREATIVE_MODE_TAB, ModUtils.makeId(name), tab);
    }

    public static void init() {}

    static {
        MAIN = registerTab("pumpkins", CreativeModeTab.builder(CreativeModeTab.Row.TOP, 0).title(Component.translatable("itemGroup."+Constants.MOD_ID)).icon(() -> {
            return new ItemStack(ModItems.SOUL_JACK_O_LANTERN);
        }).displayItems((CreativeModeTab.ItemDisplayParameters params, CreativeModeTab.Output out) -> {
            out.accept(Items.CARVED_PUMPKIN);
            out.accept(Items.JACK_O_LANTERN);
            out.accept(ModItems.SOUL_JACK_O_LANTERN);
            out.accept(ModItems.CREEPER_CARVED_PUMPKIN);
            out.accept(ModItems.CREEPER_JACK_O_LANTERN);
            out.accept(ModItems.CREEPER_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.FLOWER_CARVED_PUMPKIN);
            out.accept(ModItems.FLOWER_JACK_O_LANTERN);
            out.accept(ModItems.FLOWER_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.GHAST_CARVED_PUMPKIN);
            out.accept(ModItems.GHAST_JACK_O_LANTERN);
            out.accept(ModItems.GHAST_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.GLOBE_CARVED_PUMPKIN);
            out.accept(ModItems.GLOBE_JACK_O_LANTERN);
            out.accept(ModItems.GLOBE_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.OBSERVER_CARVED_PUMPKIN);
            out.accept(ModItems.OBSERVER_JACK_O_LANTERN);
            out.accept(ModItems.OBSERVER_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.SKELETON_CARVED_PUMPKIN);
            out.accept(ModItems.SKELETON_JACK_O_LANTERN);
            out.accept(ModItems.SKELETON_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.SNOUT_CARVED_PUMPKIN);
            out.accept(ModItems.SNOUT_JACK_O_LANTERN);
            out.accept(ModItems.SNOUT_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.ZERO_CARVED_PUMPKIN);
            out.accept(ModItems.ZERO_JACK_O_LANTERN);
            out.accept(ModItems.ZERO_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.ONE_CARVED_PUMPKIN);
            out.accept(ModItems.ONE_JACK_O_LANTERN);
            out.accept(ModItems.ONE_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.TWO_CARVED_PUMPKIN);
            out.accept(ModItems.TWO_JACK_O_LANTERN);
            out.accept(ModItems.TWO_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.THREE_CARVED_PUMPKIN);
            out.accept(ModItems.THREE_JACK_O_LANTERN);
            out.accept(ModItems.THREE_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.FOUR_CARVED_PUMPKIN);
            out.accept(ModItems.FOUR_JACK_O_LANTERN);
            out.accept(ModItems.FOUR_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.FIVE_CARVED_PUMPKIN);
            out.accept(ModItems.FIVE_JACK_O_LANTERN);
            out.accept(ModItems.FIVE_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.SIX_CARVED_PUMPKIN);
            out.accept(ModItems.SIX_JACK_O_LANTERN);
            out.accept(ModItems.SIX_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.SEVEN_CARVED_PUMPKIN);
            out.accept(ModItems.SEVEN_JACK_O_LANTERN);
            out.accept(ModItems.SEVEN_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.EIGHT_CARVED_PUMPKIN);
            out.accept(ModItems.EIGHT_JACK_O_LANTERN);
            out.accept(ModItems.EIGHT_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.NINE_CARVED_PUMPKIN);
            out.accept(ModItems.NINE_JACK_O_LANTERN);
            out.accept(ModItems.NINE_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_A_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_A_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_A_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_B_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_B_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_B_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_C_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_C_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_C_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_D_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_D_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_D_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_E_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_E_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_E_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_F_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_F_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_F_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_G_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_G_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_G_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_H_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_H_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_H_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_I_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_I_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_I_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_J_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_J_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_J_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_K_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_K_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_K_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_L_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_L_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_L_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_M_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_M_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_M_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_N_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_N_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_N_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_O_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_O_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_O_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_P_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_P_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_P_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_Q_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_Q_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_Q_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_R_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_R_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_R_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_S_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_S_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_S_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_T_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_T_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_T_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_U_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_U_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_U_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_V_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_V_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_V_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_W_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_W_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_W_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_X_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_X_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_X_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_Y_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_Y_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_Y_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_Z_CARVED_PUMPKIN);
            out.accept(ModItems.LOWERCASE_Z_JACK_O_LANTERN);
            out.accept(ModItems.LOWERCASE_Z_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_A_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_A_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_A_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_B_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_B_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_B_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_C_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_C_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_C_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_D_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_D_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_D_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_E_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_E_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_E_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_F_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_F_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_F_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_G_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_G_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_G_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_H_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_H_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_H_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_I_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_I_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_I_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_J_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_J_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_J_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_K_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_K_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_K_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_L_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_L_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_L_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_M_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_M_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_M_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_N_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_N_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_N_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_O_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_O_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_O_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_P_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_P_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_P_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_Q_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_Q_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_Q_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_R_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_R_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_R_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_S_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_S_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_S_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_T_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_T_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_T_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_U_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_U_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_U_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_V_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_V_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_V_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_W_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_W_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_W_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_X_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_X_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_X_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_Y_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_Y_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_Y_SOUL_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_Z_CARVED_PUMPKIN);
            out.accept(ModItems.UPPERCASE_Z_JACK_O_LANTERN);
            out.accept(ModItems.UPPERCASE_Z_SOUL_JACK_O_LANTERN);
        }).build());
    }
}
